<?php

namespace Database\Seeders;

use App\Models\Ministry;
use App\Models\MinistryCategory;
use App\Models\User;
use Illuminate\Database\Seeder;

class MinistrySeeder extends Seeder
{
    public function run(): void
    {
        $user = User::where('email', 'admin@horaiosbaptist.org')->first();
        $category = MinistryCategory::first();

        $ministries = [
            [
                'name' => 'Children\'s Ministry',
                'slug' => 'childrens-ministry',
                'description' => 'Nurturing young hearts and minds in the knowledge of God\'s love through age-appropriate teaching, activities, and care. Meets Sunday mornings at 9:00 AM.',
                'leader' => 'Sarah Johnson',
                'email' => 'children@horaiosbaptist.org',
                'phone' => '+855 (0) 23 123 4567',
                'featured_image' => '/images/ministries/children.jpg',
                'category_id' => $category?->id,
                'meeting_day' => 'Sunday',
                'meeting_time' => '09:00',
                'location' => 'Children\'s Wing, Main Building',
                'featured' => true,
                'status' => 'published',
                'published_at' => now()->subDays(60),
                'display_order' => 1,
                'seo_title' => 'Children\'s Ministry - Horaios Baptist Church',
                'seo_description' => 'Our children\'s ministry provides age-appropriate biblical teaching and activities for kids from nursery through elementary school.',
                'created_by' => $user?->id,
                'updated_by' => $user?->id,
            ],
            [
                'name' => 'Youth Ministry',
                'slug' => 'youth-ministry',
                'description' => 'Empowering the next generation to live out their faith through worship, fellowship, and service opportunities. Meets Wednesday evenings at 7:00 PM.',
                'leader' => 'David Chen',
                'email' => 'youth@horaiosbaptist.org',
                'phone' => '+855 (0) 23 234 5678',
                'featured_image' => '/images/ministries/youth.jpg',
                'category_id' => $category?->id,
                'meeting_day' => 'Wednesday',
                'meeting_time' => '19:00',
                'location' => 'Youth Center, Main Building',
                'featured' => true,
                'status' => 'published',
                'published_at' => now()->subDays(60),
                'display_order' => 2,
                'seo_title' => 'Youth Ministry - Horaios Baptist Church',
                'seo_description' => 'Join our youth ministry for teens. Worship, fellowship, and service opportunities for the next generation.',
                'created_by' => $user?->id,
                'updated_by' => $user?->id,
            ],
            [
                'name' => 'Worship Ministry',
                'slug' => 'worship-ministry',
                'description' => 'Leading the congregation in authentic worship through music, art, and creative expression that honors God. Meets Thursday evenings at 7:00 PM.',
                'leader' => 'Michael Williams',
                'email' => 'worship@horaiosbaptist.org',
                'phone' => '+855 (0) 23 345 6789',
                'featured_image' => '/images/ministries/worship.jpg',
                'category_id' => $category?->id,
                'meeting_day' => 'Thursday',
                'meeting_time' => '19:00',
                'location' => 'Main Sanctuary',
                'featured' => true,
                'status' => 'published',
                'published_at' => now()->subDays(60),
                'display_order' => 3,
                'seo_title' => 'Worship Ministry - Horaios Baptist Church',
                'seo_description' => 'Join our worship ministry team. Musicians, vocalists, and technical team members welcome.',
                'created_by' => $user?->id,
                'updated_by' => $user?->id,
            ],
            [
                'name' => 'Outreach Ministry',
                'slug' => 'outreach-ministry',
                'description' => 'Serving our local community through food distribution, visitation programs, and partnership with local organizations. Meets Saturday mornings at 8:00 AM.',
                'leader' => 'Lisa Park',
                'email' => 'outreach@horaiosbaptist.org',
                'phone' => '+855 (0) 23 456 7890',
                'featured_image' => '/images/ministries/outreach.jpg',
                'category_id' => $category?->id,
                'meeting_day' => 'Saturday',
                'meeting_time' => '08:00',
                'location' => 'Church Parking Lot & Community Center',
                'featured' => false,
                'status' => 'published',
                'published_at' => now()->subDays(60),
                'display_order' => 4,
                'seo_title' => 'Outreach Ministry - Horaios Baptist Church',
                'seo_description' => 'Serve our local community through food distribution, visitation programs, and partnership with local organizations.',
                'created_by' => $user?->id,
                'updated_by' => $user?->id,
            ],
            [
                'name' => 'Men\'s Ministry',
                'slug' => 'mens-ministry',
                'description' => 'Building strong men of faith through fellowship, accountability, and practical teaching for daily living. Meets Tuesday mornings at 6:30 AM.',
                'leader' => 'James Brown',
                'email' => 'men@horaiosbaptist.org',
                'phone' => '+855 (0) 23 567 8901',
                'featured_image' => '/images/ministries/men.jpg',
                'category_id' => $category?->id,
                'meeting_day' => 'Tuesday',
                'meeting_time' => '06:30',
                'location' => 'Fellowship Hall',
                'featured' => false,
                'status' => 'published',
                'published_at' => now()->subDays(60),
                'display_order' => 5,
                'seo_title' => 'Men\'s Ministry - Horaios Baptist Church',
                'seo_description' => 'Join our men\'s ministry for fellowship, accountability, and practical teaching. Tuesday morning breakfast and Bible study.',
                'created_by' => $user?->id,
                'updated_by' => $user?->id,
            ],
            [
                'name' => 'Women\'s Ministry',
                'slug' => 'womens-ministry',
                'description' => 'Encouraging women in their faith journey through Bible studies, prayer groups, and meaningful relationships. Meets Monday mornings at 10:00 AM.',
                'leader' => 'Maria Garcia',
                'email' => 'women@horaiosbaptist.org',
                'phone' => '+855 (0) 23 678 9012',
                'featured_image' => '/images/ministries/women.jpg',
                'category_id' => $category?->id,
                'meeting_day' => 'Monday',
                'meeting_time' => '10:00',
                'location' => 'Fellowship Hall',
                'featured' => false,
                'status' => 'published',
                'published_at' => now()->subDays(60),
                'display_order' => 6,
                'seo_title' => 'Women\'s Ministry - Horaios Baptist Church',
                'seo_description' => 'Join our women\'s ministry for Bible studies, prayer groups, and meaningful relationships. Monday morning gatherings.',
                'created_by' => $user?->id,
                'updated_by' => $user?->id,
            ],
            [
                'name' => 'Prayer Ministry',
                'slug' => 'prayer-ministry',
                'description' => 'Interceding for our church, community, and world through regular prayer meetings and prayer chains. Meets Wednesday evenings at 6:00 PM.',
                'leader' => 'Thomas Lee',
                'email' => 'prayer@horaiosbaptist.org',
                'phone' => '+855 (0) 23 789 0123',
                'featured_image' => '/images/ministries/prayer.jpg',
                'category_id' => $category?->id,
                'meeting_day' => 'Wednesday',
                'meeting_time' => '18:00',
                'location' => 'Prayer Room, Main Building',
                'featured' => false,
                'status' => 'published',
                'published_at' => now()->subDays(60),
                'display_order' => 7,
                'seo_title' => 'Prayer Ministry - Horaios Baptist Church',
                'seo_description' => 'Join our prayer ministry for regular prayer meetings and prayer chains. Interceding for our church, community, and world.',
                'created_by' => $user?->id,
                'updated_by' => $user?->id,
            ],
            [
                'name' => 'Media Ministry',
                'slug' => 'media-ministry',
                'description' => 'Supporting church services and events through audio, video, and lighting production for effective communication. Serves on Sunday mornings at 8:00 AM.',
                'leader' => 'Kevin Miller',
                'email' => 'media@horaiosbaptist.org',
                'phone' => '+855 (0) 23 890 1234',
                'featured_image' => '/images/ministries/media.jpg',
                'category_id' => $category?->id,
                'meeting_day' => 'Sunday',
                'meeting_time' => '08:00',
                'location' => 'Sound Booth & Control Room',
                'featured' => false,
                'status' => 'published',
                'published_at' => now()->subDays(60),
                'display_order' => 8,
                'seo_title' => 'Media Ministry - Horaios Baptist Church',
                'seo_description' => 'Join our media ministry team. Audio, video, and lighting production for church services and events.',
                'created_by' => $user?->id,
                'updated_by' => $user?->id,
            ],
        ];

        foreach ($ministries as $ministry) {
            Ministry::updateOrCreate(
                ['slug' => $ministry['slug']],
                $ministry
            );
        }

        $this->command->info('Ministries seeded successfully.');
    }
}
